version: '3'

services:
  app:
    build:
      context: .
    container_name: golang
    image: dipaschoal/desafio-golang:latest
    networks:
      - golang-network
    ports:
      - "8080:8080"
networks:
  golang-network:
    driver: bridge
